# This is a basic workflow to help you get started with Actions

name: wp-congee

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs rsync deployments script
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -Oavzr --delete --exclude="config.yaml"
        path: ./
        remote_path: /opt/bitnami/apps/typo3/htdocs/install/typo3conf/sites/congee
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
